training:
  max_epochs: 1
  batch_size: 16
  peak_learning_rate: 4.0e-4
  warmup_steps: 2000
  total_steps: 100000
  end_learning_rate: 4.0e-5
  weight_decay: 0.1
  gradient_accumulation_steps: 2
  evaluation_frequency: 500
  maximum_evaluation_steps: 500
  staged_warmup_steps: 1000001
  warmup_train_context: 1024

model:
  size: "solu-6l"
  precision: "float32"

data:
  corpus: "openwebtext"
  max_context: 4096
  train_samples: 14809244
  checkpoint_directory: "checkpoints"
  shard_path_train: "data/index/openwebtext2_train_useast.index"
  shard_path_validation: "data/index/openwebtext2_validation_useast.index"
  wandb_project: "jax-transformer-micro"
  resume_step: 0
  wandb_id: ""