training:
  max_epochs: 20
  batch_size: 256
  peak_learning_rate: 6.0e-4
  warmup_steps: 2000
  total_steps: 210000
  end_learning_rate: 6.0e-5
  weight_decay: 0.1
  gradient_accumulation_steps: 8
  evaluation_frequency: 1000
  maximum_evaluation_steps: 250
  staged_warmup_steps: 107000
  warmup_train_context: 128

model:
  size: "gpt2small"

data:
  corpus: "openwebtext"
  max_context: 1024
  train_samples: 3525038
  checkpoint_directory: "checkpoints"
  bucket_path: "bfattoribookseu"
  index_path_train: "data/index/openwebtext.traineu.index"
  index_path_validation: "data/index/openwebtext.valeu.index"
  wandb_project: "jax-transformer-fast"
  resume_step: 0


