training:
  max_epochs: 2
  batch_size: 16
  peak_learning_rate: 6e-4
  warmup_steps: 2000
  decay_steps: 24000
  total_steps: 24500
  end_learning_rate: 6e-5
  weight_decay: 0.1
  gradient_accumulation_steps: 32
  evaluation_frequency: 500
  maximum_evaluation_steps: 500
  precision: 'bf16'
  # staged_sequences: [128]
  staged_sequences: []
  staged_warmup_steps: 6000

model:
  size: "base"

data:
  corpus: "openwebtext"
  train_shard_urls: "data/processed/sharded/openwebtext_train-{000000..000125}.tar.gz"
  validation_shard_urls: "data/processed/sharded/openwebtext_val-{000000..000008}.tar.gz"
  max_context: 1024
  full_steps_in_batch: 24558
  workers: 0
  checkpoint_directory: "checkpoints"
  bucket_path: "bfattoriwebtext2"
  # bucket_path: 
  index_path_train: "data/index/openwebtext_useast.train.index"
  index_path_validation: "data/index/openwebtext_useast.val.index"

device:
  dp_devices:
  mp_devices: 