training:
  max_epochs: 20
  batch_size: 64
  peak_learning_rate: 2.0e-4
  warmup_steps: 2000
  decay_steps: 9500
  total_steps: 10000
  end_learning_rate: 2.0e-5
  weight_decay: 0.1
  gradient_accumulation_steps: 8
  evaluation_frequency: 500
  maximum_evaluation_steps: 500
  precision: 'fp32'
  staged_warmup_steps: 100001
  warmup_train_context: 1024

model:
  size: "large"
  warm_start: True
  model_path: "warmstart_params/large_params.msgpack"

data:
  corpus: "openwebtext"
  train_shard_urls:
  validation_shard_urls: 
  max_context: 2048
  train_samples: 9741373
  checkpoint_directory: "checkpoints"
  bucket_path: "bfattoriwebtext2"
  index_path_train: "data/index/openwebtext_extended_useast.train.index"
  index_path_validation: "data/index/openwebtext_extended_useast.val.index"
  wandb_project: "jax-transformer"


device: 
  dp_devices: 32
  mp_devices: 1