training:
  max_epochs: 20
  batch_size: 32
  peak_learning_rate: 6.0e-4
  warmup_steps: 2000
  total_steps: 230000
  end_learning_rate: 3.0e-5
  weight_decay: 0.1
  gradient_accumulation_steps: 4
  evaluation_frequency: 1000
  maximum_evaluation_steps: 500
  staged_warmup_steps: 1000001
  warmup_train_context: 2048

model:
  size: "solu-1l"

data:
  corpus: "openwebtext"
  max_context: 4096
  train_samples: 14809244
  checkpoint_directory: "checkpoints"
  shard_path_train: "data/index/openwebtext2_train.index"
  shard_path_validation: "data/index/openwebtext2_validation.index"
  wandb_project: "jax-transformer"
  resume_step: 2000