training:
  max_epochs: 20
  batch_size: 256
  peak_learning_rate: 6.0e-4
  warmup_steps: 2000
  total_steps: 25000
  end_learning_rate: 6.0e-4
  weight_decay: 0.1
  gradient_accumulation_steps: 64
  evaluation_frequency: 500
  maximum_evaluation_steps: 500
  train_context: 1024

model:
  size: "base"
  warm_start: False
  model_path: "warmstart_params/warmstart_params_XXL.msgpack"

data:
  corpus: "openwebtext"
  max_context: 2048
  train_samples: 14809244
  checkpoint_directory: "checkpoints"
  bucket_path: "bfattoriwebtext2"
  index_path_train: "data/index/openwebtext_useast.train.index"
  index_path_validation: "data/index/openwebtext_useast.val.index"
  wandb_project: "jax-transformer"
  resume_step: 0