training:
  max_epochs: 20
  batch_size: 64
  peak_learning_rate: 8e-4
  warmup_steps: 2000
  decay_steps: 107500
  total_steps: 110000
  end_learning_rate: 8e-5
  weight_decay: 0.1
  gradient_accumulation_steps: 2
  evaluation_frequency: 500
  maximum_evaluation_steps: 500
  precision: 'bf16'
  staged_warmup_steps: -1
  warmup_train_context: 2048

model:
  size: "smol"

data:
  corpus: "openwebtext"
  train_shard_urls:
  validation_shard_urls: 
  max_context: 2048
  full_steps_in_batch: 13769
  checkpoint_directory: "checkpoints"
  bucket_path: "bfattoriwebtext2"
  index_path_train: "data/index/openwebtext_useast.train.index"
  index_path_validation: "data/index/openwebtext_useast.val.index"
  wandb_project: "jax-transformer"


device: 
  dp_devices: 32
  mp_devices: 1