QA:
  embedding_dim: 128
  vocab_size: 50257
  num_head: 16
  block_size: 1024
  dropout: 0.0
  N: 2
  fused_residuals: True
  alibi_attn: True

unittest:
  embedding_dim: 768
  vocab_size: 50257
  num_head: 12
  block_size: 1024
  dropout: 0.0
  N: 12
  fused_residuals: True
  alibi_attn: True

small:
  embedding_dim: 64
  vocab_size: 50258
  num_head: 8
  block_size: 512
  dropout: 0.1
  N: 2
  fused_residuals: True
  alibi_attn: True

test:
  embedding_dim: 128
  vocab_size: 50264
  num_head: 4
  block_size: 32
  dropout: 0.1
  N: 2
  fused_residuals: True
  alibi_attn: True

smol:
  embedding_dim: 768
  vocab_size: 50432
  num_head: 12
  block_size: 2048
  dropout: 0.1
  N: 6
  fused_residuals: False
  alibi_attn: True

base:
  embedding_dim: 768
  vocab_size: 50304
  num_head: 16
  block_size: 1024
  dropout: 0.1
  N: 12
  fused_residuals: False
  alibi_attn: True

bytelevelbase:
  embedding_dim: 1024
  vocab_size: 384
  num_head: 16
  block_size: 4096
  dropout: 0.1
  N: 10
  fused_residuals: False
  alibi_attn: True

medium:
  embedding_dim: 1024
  vocab_size: 50304
  num_head: 16
  block_size: 1024
  dropout: 0.1
  N: 20
  fused_residuals: True
  alibi_attn: True


large: #around 580M
  embedding_dim: 1536
  vocab_size: 50304
  num_head: 12
  block_size: 1024
  dropout: 0.1
  N: 18
  fused_residuals: False
  alibi_attn: True

XL: #around 780M
  embedding_dim: 1536
  vocab_size: 50304
  num_head: 12
  block_size: 1024
  dropout: 0.1
  N: 24
  fused_residuals: False
  alibi_attn: True

XXL: #around 1.1B
  embedding_dim: 1536
  vocab_size: 50304
  num_head: 12
  block_size: 1024
  dropout: 0.1
  N: 36
  fused_residuals: False
  alibi_attn: True
