test_remat:
  embedding_dim: 64
  vocab_size: 256
  num_head: 8
  block_size: 32
  dropout: 0.0
  N: 2
  alibi_attn: True
  gradient_remat: True

test:
  embedding_dim: 64
  vocab_size: 256
  num_head: 16
  block_size: 32
  dropout: 0.0
  N: 4
  alibi_attn: True
  gradient_remat: False

base:
  embedding_dim: 768
  vocab_size: 50304
  num_head: 12
  block_size: 1024
  dropout: 0.1
  N: 12
  alibi_attn: True

1_3b:
  embedding_dim: 2048
  vocab_size: 50304
  num_head: 16
  block_size: 1024
  dropout: 0.1
  N: 24
  alibi_attn: True

760m:
  embedding_dim: 1536
  vocab_size: 50304
  num_head: 16
  block_size: 1024
  dropout: 0.1
  N: 24
  alibi_attn: True

417m:
  embedding_dim: 1536
  vocab_size: 50304
  num_head: 16
  block_size: 1024
  dropout: 0.1
  N: 12
  alibi_attn: True
  gradient_remat: False


2_7b:
  embedding_dim: 5120
  vocab_size: 50304
  num_head: 40
  block_size: 1024
  dropout: 0.0
  N: 7
  alibi_attn: True
  gradient_remat: True
