QA:
  embedding_dim: 256
  vocab_size: 50257
  num_head: 8
  block_size: 512
  dropout: 0.0
  N: 3
  fused_residuals: True
  alibi_attn: True
  

small:
  embedding_dim: 768
  vocab_size: 50257
  num_head: 8
  block_size: 512
  dropout: 0.0
  N: 6
  fused_residuals: True
  alibi_attn: True
  head_qk_trick: True
  
base:
  embedding_dim: 768
  vocab_size: 50257
  num_head: 12
  block_size: 512
  dropout: 0.0
  N: 12
  fused_residuals: True
  alibi_attn: False

medium:
  embedding_dim: 1024
  vocab_size: 50257
  num_head: 16
  block_size: 512
  dropout: 0.0
  N: 24
  fused_residuals: True
  alibi_attn: False