QA:
  embedding_dim: 128
  vocab_size: 50257
  num_head: 16
  block_size: 1024
  dropout: 0.0
  N: 2
  fused_residuals: True
  alibi_attn: True

unittest:
  embedding_dim: 768
  vocab_size: 50257
  num_head: 12
  block_size: 1024
  dropout: 0.0
  N: 12
  fused_residuals: True
  alibi_attn: True

small:
  embedding_dim: 256
  vocab_size: 50258
  num_head: 8
  block_size: 1024
  dropout: 0.5
  N: 4
  fused_residuals: True
  alibi_attn: True

  
base:
  embedding_dim: 768
  vocab_size: 50258
  num_head: 12
  block_size: 512
  dropout: 0.1
  N: 12
  fused_residuals: True
  alibi_attn: True

medium:
  embedding_dim: 1024
  vocab_size: 50258
  num_head: 16
  block_size: 1024
  dropout: 0.0
  N: 24
  fused_residuals: True
  alibi_attn: True


large:
  embedding_dim: 1536
  vocab_size: 50258
  num_head: 16
  block_size: 1024
  dropout: 0.0
  N: 24
  fused_residuals: True
  alibi_attn: True

XL:
  embedding_dim: 2048
  vocab_size: 50257
  num_head: 16
  block_size: 1024
  dropout: 0.0
  N: 24
  fused_residuals: True
  alibi_attn: True