test:
  embedding_dim: 64
  vocab_size: 256
  num_head: 4
  block_size: 32
  dropout: 0.0
  N: 2
  alibi_attn: True

1_3b:
  embedding_dim: 2048
  vocab_size: 50304
  num_head: 16
  block_size: 1024
  dropout: 0.1
  N: 24
  alibi_attn: True

760m:
  embedding_dim: 1536
  vocab_size: 50304
  num_head: 16
  block_size: 1024
  dropout: 0.1
  N: 24
  alibi_attn: True

417m:
  embedding_dim: 1536
  vocab_size: 50304
  num_head: 12
  block_size: 2048
  dropout: 0.1
  N: 12
  alibi_attn: True
